apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant-service
  namespace: food-delivery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restaurant-service
  template:
    metadata:
      labels:
        app: restaurant-service
    spec:
      containers:
        - name: restaurant-service
          image: food-delivery-restaurant-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 5002
              protocol: TCP
          envFrom:
            - configMapRef:
                name: restaurant-service-config
            - secretRef:
                name: restaurant-service-secret
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
